export const LOGIN = 'LOGIN';
export const REQUEST_QUESTION_SUCCESS = 'REQUEST_QUESTION_SUCCESS';
export const REQUEST_QUESTION_PROCESS = 'REQUEST_QUESTION_PROCESS';
export const REQUEST_QUESTION_FAIL = 'REQUEST_QUESTION_FAIL';
export const TIME_OUT = 'TIME_OUT';
